apiVersion: apps/v1
kind: Deployment
metadata:
  name: hennie-belt-exam-database-deployment
  namespace: hennie-belt-exam
  labels:
    app: hennie-belt-exam
spec:
  selector:
    matchLabels:
      app: hennie-belt-exam
  replicas: 1
  template:
    metadata:
      labels:
        app: hennie-belt-exam
    spec:
      containers:
      - name: hennie-belt-exam-database
        image: postgres:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "admin123"
        - name: POSTGRES_DB
          value: "basic3tier"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"